---
_links:
  self:
    href: https://vsrm.dev.azure.com/billbirch/078de0b6-681d-4a52-a11f-7cf81bb72ffe/_apis/Release/definitions/1
  web:
    href: https://dev.azure.com/billbirch/078de0b6-681d-4a52-a11f-7cf81bb72ffe/_release?definitionId=1
artifacts: []
createdBy:
  _links:
    avatar:
      href: https://dev.azure.com/billbirch/_apis/GraphProfile/MemberAvatars/aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
  descriptor: aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
  displayName: Bill Birch
  id: b080fb0c-6bb8-6a6d-ae60-1003210bc5bc
  imageUrl: https://dev.azure.com/billbirch/_apis/GraphProfile/MemberAvatars/aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
  uniqueName: bill.birch@coles.com.au
  url: https://spsprodeau1.vssps.visualstudio.com/Abc5b2252-126c-45ee-9c98-0a57a82abb42/_apis/Identities/b080fb0c-6bb8-6a6d-ae60-1003210bc5bc
createdOn: "2020-02-04T04:55:18.200Z"
description: null
environments:
- badgeUrl: https://vsrm.dev.azure.com/billbirch/_apis/public/Release/badge/078de0b6-681d-4a52-a11f-7cf81bb72ffe/1/1
  conditions:
  - conditionType: 1
    name: ReleaseStarted
    value: ""
  currentRelease:
    _links: {}
    id: 0
    url: https://vsrm.dev.azure.com/billbirch/078de0b6-681d-4a52-a11f-7cf81bb72ffe/_apis/Release/releases/0
  demands: []
  deployPhases:
  - deploymentInput:
      agentSpecification:
        identifier: vs2017-win2016
      artifactsDownloadInput:
        downloadInputs: []
      condition: succeeded()
      demands: []
      enableAccessToken: false
      jobCancelTimeoutInMinutes: 1
      overrideInputs: {}
      parallelExecution:
        parallelExecutionType: 0
      queueId: 9
      skipArtifactsDownload: false
      timeoutInMinutes: 0
    name: Agent job
    phaseType: 1
    rank: 1
    refName: null
    workflowTasks: []
  deployStep:
    id: 2
  environmentOptions:
    autoLinkWorkItems: false
    badgeEnabled: false
    emailNotificationType: OnlyOnFailure
    emailRecipients: release.environment.owner;release.creator
    enableAccessToken: false
    publishDeploymentStatus: true
    pullRequestDeploymentEnabled: false
    skipArtifactsDownload: false
    timeoutInMinutes: 0
  environmentTriggers: []
  executionPolicy:
    concurrencyCount: 1
    queueDepthCount: 0
  id: 1
  name: Stage 1
  owner:
    _links:
      avatar:
        href: https://dev.azure.com/billbirch/_apis/GraphProfile/MemberAvatars/aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
    descriptor: aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
    displayName: Bill Birch
    id: b080fb0c-6bb8-6a6d-ae60-1003210bc5bc
    imageUrl: https://dev.azure.com/billbirch/_apis/GraphProfile/MemberAvatars/aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
    uniqueName: bill.birch@coles.com.au
    url: https://spsprodeau1.vssps.visualstudio.com/Abc5b2252-126c-45ee-9c98-0a57a82abb42/_apis/Identities/b080fb0c-6bb8-6a6d-ae60-1003210bc5bc
  postDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: 2
      releaseCreatorCanBeApprover: false
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - id: 3
      isAutomated: true
      isNotificationOn: false
      rank: 1
  postDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  preDeployApprovals:
    approvalOptions:
      autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped: false
      enforceIdentityRevalidation: false
      executionOrder: 1
      releaseCreatorCanBeApprover: false
      requiredApproverCount: null
      timeoutInMinutes: 0
    approvals:
    - id: 1
      isAutomated: true
      isNotificationOn: false
      rank: 1
  preDeploymentGates:
    gates: []
    gatesOptions: null
    id: 0
  processParameters: {}
  properties:
    BoardsEnvironmentType:
      $type: System.String
      $value: unmapped
    LinkBoardsWorkItems:
      $type: System.String
      $value: "False"
  rank: 1
  retentionPolicy:
    daysToKeep: 30
    releasesToKeep: 3
    retainBuild: true
  schedules: []
  variableGroups: []
  variables: {}
id: 1
isDeleted: false
modifiedBy:
  _links:
    avatar:
      href: https://dev.azure.com/billbirch/_apis/GraphProfile/MemberAvatars/aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
  descriptor: aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
  displayName: Bill Birch
  id: b080fb0c-6bb8-6a6d-ae60-1003210bc5bc
  imageUrl: https://dev.azure.com/billbirch/_apis/GraphProfile/MemberAvatars/aad.YjA4MGZiMGMtNmJiOC03YTZkLWFlNjAtMTAwMzIxMGJjNWJj
  uniqueName: bill.birch@coles.com.au
  url: https://spsprodeau1.vssps.visualstudio.com/Abc5b2252-126c-45ee-9c98-0a57a82abb42/_apis/Identities/b080fb0c-6bb8-6a6d-ae60-1003210bc5bc
modifiedOn: "2020-02-04T04:55:18.200Z"
name: New release pipeline
path: \rel.yaml
projectReference: null
properties:
  DefinitionCreationSource:
    $type: System.String
    $value: ReleaseNew
  IntegrateBoardsWorkItems:
    $type: System.String
    $value: "False"
  IntegrateJiraWorkItems:
    $type: System.String
    $value: "false"
releaseNameFormat: Release-$(rev:r)
revision: 1
source: 2
tags: []
triggers: []
url: https://vsrm.dev.azure.com/billbirch/078de0b6-681d-4a52-a11f-7cf81bb72ffe/_apis/Release/definitions/1
variableGroups: []
variables: {}
